version: '3'
services:
  app:
    container_name: rest_api_jwt_pdv_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db 
    networks:
      - pdv_jwt

  db:
    image: postgres
    container_name: rest_api_jwt_pdv_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - pdv_jwt

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "lucas.silva.silveira@rede.ulbra.br"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - db

volumes:
  api:
  db_postgres:

# Networks to be created to facilitate communication between containers
networks:
  pdv_jwt: