version: '3'
services:
  app:
    container_name: rest_api_jwt_pdv_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - rest_api:/usr/src/app/
    depends_on:
      - db 
    networks:
      - pdv_jwt

  db:
    image: postgres
    container_name: rest_api_jwt_pdv_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - pdv_jwt

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "lucas.silva.silveira@rede.ulbra.br"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5454:80"
    depends_on:
      - db

volumes:
  rest_api:
  database:

networks:
  pdv_jwt: